---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure the target directory exists
  file:
    path: /home/deploy/main-news-telegram-bot
    state: directory
    owner: deploy
    group: deploy

- name: Copy binary to remote host
  copy:
    src: ../../../bot
    dest: /home/deploy/main-news-telegram-bot/bot
    owner: deploy
    group: deploy
    mode: '0755'

- name: Copy binary to remote host
  copy:
    src: ../../../send_news
    dest: /home/deploy/main-news-telegram-bot/send_news
    owner: deploy
    group: deploy
    mode: '0755'

- name: Copy systemd service file
  template:
    src: main-news-telegram-bot.service.j2
    dest: /etc/systemd/system/main-news-telegram-bot.service

- name: Reload systemd to recognize new service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start and enable the service
  ansible.builtin.systemd_service:
    name: main-news-telegram-bot
    enabled: true
    state: restarted

- name: Copy .env file
  template:
    src: env.j2
    dest: /home/deploy/main-news-telegram-bot/.env
    owner: deploy
    group: deploy

- name: Add cron job to run send_news every hour
  cron:
    name: "Run send_news every hour"
    minute: "0"
    hour: "*"
    job: "cd /home/deploy/main-news-telegram-bot && ./send_news > cron_output.txt 2>&1"
    user: deploy
